apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appname }}-ingress
  annotations:
   kubernetes.io/ingress.class: {{ .Values.ingress.class }}
   nginx.ingress.kubernetes.io/proxy-connect-timeout: "14400"
   nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
   nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
   nginx.ingress.kubernetes.io/ssl-redirect: "false"
   nginx.org/websocket-services: {{ .Values.appname }}-service
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appname }}-service
          servicePort: 80
