apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-service
  labels:
    app: {{ .Values.appname }}
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 4000
  selector:
    app: {{ .Values.appname }}
